### ISSUE TITLE
Broken template for addonRoutes and addonReducers

### ISSUE THREAD

**Issue by avoinea** [plone/generator-volto#5]
https://github.com/plone/generator-volto/blob/cc09b81ed125356dfabe0e8390d00b07ef4f30e9/generators/app/templates/src/config.js#L38-L39

it should be:

https://github.com/plone/create-volto-app/blob/0b2f16228d87e89c6ba18f22ad2d0d9832106121/volto-starter-kit/src/config.js#L40-L41

**Comment by nileshgulia1** [comment]
Was having problems connecting reducers. Thanks @avoinea  PR created. #6
